name: Automatización Horaria AgroAlert

on:
  schedule:
    # Se ejecuta automáticamente cada hora en punto y a y media
    - cron: '0,30 * * * *'
  workflow_dispatch:

jobs:
  comprobar-y-enviar:
    runs-on: ubuntu-latest
    steps:
      - name: Descargar código del repositorio
        uses: actions/checkout@v4

      - name: Configurar Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Instalar dependencias
        run: |
          pip install pandas streamlit folium streamlit-folium

      - name: Ejecutar comprobación de horarios
        run: |
          python app.py
